# Generated by Django 5.1.4 on 2025-01-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_rue', models.IntegerField(verbose_name='Numéro de la rue')),
                ('nom_rue', models.CharField(max_length=100, verbose_name='Nom de la rue')),
                ('img_client', models.ImageField(upload_to='images/', verbose_name='Image du client')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='Esdeath', max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(default='Hinata', max_length=100, verbose_name='Prénom')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Mapping.adresse', verbose_name='Adresse')),
            ],
        ),
    ]
