# Generated by Django 5.1.3 on 2025-01-15 18:28

import django.db.models.deletion
import jsonfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectexposer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('numero_marchandise', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('numero_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('marchandises', jsonfield.fields.JSONField(default=dict)),
                ('montant_total', models.FloatField(default=0.0)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProjectexposer.client')),
            ],
        ),
    ]
