# Generated by Django 5.1.5 on 2025-02-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProjectexposer', '0002_marchandise_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
